server:
  port: 8083
  context-path: /

spring:
  application:
    name: accountservice
  profiles:
      active: dev
  datasource:
    url: jdbc:mysql://47.106.207.69:3306/account?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: panxl
    password: 123456pxl
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  typeAliasesPackage: com.pxl.account.entity
  mapperLocations: classpath:com/pxl/account/mapperxml/*.xml
