server:
  port: 8082
  context-path: /

spring:
  application:
    name: account-service
  profiles:
      active: dev
  datasource:
    url: jdbc:mysql://47.106.207.69:3306/account?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: panxl
    password: 123456pxl
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  typeAliasesPackage: com.pxl.account.entity
  mapperLocations: classpath:mapper/*.xml

fescar:
  group:
    name: test_group
