spring:
  cloud:
    consul:
      discovery:
        health-check-path: /healths
        prefer-ip-address: true
        health-check-interval: 300s

management:
  health:
    consul:
      enabled: false