server:
  port: 8084
  context-path: /

spring:
  application:
    name: order-service
  profiles:
      active: dev
  datasource:
    url: jdbc:mysql://47.106.207.69:3306/order?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: panxl
    password: 123456pxl
    type: com.alibaba.druid.pool.DruidDataSource

feign:
  remote:
    ##调用商品微服务名称
    commodity-service: commodity-service
    ##调用账户微服务名称
    account-service: account-service
